# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: ms_user
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  redis:
    extends:
      file: ./redis.yml
      service: redis
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
